In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
x1 = pd.read_csv("t1_1.csv")
y1 = pd.read_csv("t10_1.csv")
x2 = pd.read_csv("t11_1.csv")
y2 = pd.read_csv("t12_1.csv")
x3 = pd.read_csv("t10_2.csv")
y3 = pd.read_csv("t1_2.csv")
x4 = pd.read_csv("t12_2.csv")
y4 = pd.read_csv("t11_2.csv")

In [3]:
# x1 -> y1, y2, y4

df1 = pd.DataFrame()
df1 = pd.concat([y1, y2], axis=1)
df1 = pd.concat([df1, y4], axis=1)

In [4]:
X_1 = x1[['교통량']]
y_1 = df1[['교통량']]

In [5]:
model1 = LinearRegression()
model1.fit(X_1, y_1)
y_predict1 = model1.predict(X_1)

In [6]:
print(model1.intercept_)
print(model1.coef_)
print(model1.score(X_1, y_1))

[ -6.83429156 -23.56641728 -15.1183534 ]
[[0.98022624]
 [0.74164842]
 [0.64819649]]
0.9372305035576607


D:\Anaconda\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


In [7]:
# x2 -> y1, y2, y3

df2 = pd.DataFrame()
df2 = pd.concat([y1, y2], axis=1)
df2 = pd.concat([df2, y3], axis=1)

In [8]:
X_2 = x2[['교통량']]
y_2 = df2[['교통량']]

In [9]:
model2 = LinearRegression()
model2.fit(X_2, y_2)
y_predict2 = model2.predict(X_2)

In [10]:
print(model2.intercept_)
print(model2.coef_)
print(model2.score(X_2, y_2))

[48.56495109 -5.29061871 40.3542097 ]
[[1.43913531]
 [1.19237395]
 [1.63459064]]
0.918191548906298


D:\Anaconda\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


In [11]:
# x3 -> y2, y3, y4

df3 = pd.DataFrame()
df3 = pd.concat([y2, y3], axis=1)
df3 = pd.concat([df3, y4], axis=1)

In [12]:
X_3 = x3[['교통량']]
y_3 = df3[['교통량']]

In [13]:
model3 = LinearRegression()
model3.fit(X_3, y_3)
y_predict3 = model3.predict(X_3)

In [14]:
print(model3.intercept_)
print(model3.coef_)
print(model3.score(X_3, y_3))

[-2.26672735  6.80616826  5.70455071]
[[0.65138532]
 [0.98414135]
 [0.56396833]]
0.9361755406154664


D:\Anaconda\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)


In [15]:
# x4 -> y1, y3, y4

df4 = pd.DataFrame()
df4 = pd.concat([y1, y3], axis=1)
df4 = pd.concat([df4, y4], axis=1)

In [16]:
X_4 = x4[['교통량']]
y_4 = df4[['교통량']]

In [17]:
model4 = LinearRegression()
model4.fit(X_4, y_4)
y_predict4 = model4.predict(X_4)

In [18]:
print(model4.intercept_)
print(model4.coef_)
print(model4.score(X_4, y_4))

[60.53467082 61.12700149  2.90917467]
[[1.14599797]
 [1.27566917]
 [0.85378695]]
0.8574040460240676


D:\Anaconda\lib\site-packages\sklearn\base.py:420: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)
